const bcrypt = require('bcryptjs');

const data = {
    users: [
        {
            name: 'Caliche',
            email: 'admin@example.com',
            password: bcrypt.hashSync('123456'),
            isAdmin: true,
        },
        {
            name: 'John',
            email: 'user@example.com',
            password: bcrypt.hashSync('123456'),
            isAdmin: false,
        },
    ],
    products: [
        {
            // _id:'1',
            name: 'Nike_Slim_shirt_1',
            slug: 'Nike_slim_shirt_1',
            category: 'Shirts',
            image: '/images/c1.jpg',
            price: 120,
            countinstock: 2,
            brand: 'Nike',
            rating: 4.0,
            numReviews: '10',
            description: 'high quality shirt',
        },
        {
            // _id:'2',
            name: 'Adidas_Slim_shirt_2',
            slug: 'Adidas_slim_shirt_2',
            category: 'Shirts',
            image: '/images/c2.jpg',
            price: 120,
            countinstock: 10,
            brand: 'Adidas',
            rating: 4.5,
            numReviews: '10',
            description: 'high quality shirt',


        },
        {
            // _id:'3',
            name: 'Nike_Slim_Pant_3',
            slug: 'nike_slim_Pant_3',
            category: 'Pants',
            image: '/images/c3.jpg',
            price: 120,
            countinstock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: '10',
            description: 'high quality Pant',
        },
        {
            // _id:'4',
            name: 'Adidas_Slim_Pant_4',
            slug: 'Adidas_slim_Pant_4',
            category: 'Shirts',
            image: '/images/c4.jpg',
            price: 120,
            countinstock: 10,
            brand: 'Adidas',
            rating: 4.5,
            numReviews: '10',
            description: 'high quality Pant',
        },
        {
            // _id:'5',
            name: 'Adidas_Slim_Pant_5',
            slug: 'Adidas_slim_Pant_5',
            category: 'Shirts',
            image: '/images/c5.jpg',
            price: 120,
            countinstock: 10,
            brand: 'Adidas',
            rating: 4.5,
            numReviews: '10',
            description: 'high quality Pant',
        },
        {
            // _id:'6',
            name: 'Adidas_Slim_Pant_6',
            slug: 'Adidas_slim_Pant_6',
            category: 'Shirts',
            image: '/images/c6.jpg',
            price: 120,
            countinstock: 10,
            brand: 'Adidas',
            rating: 4.5,
            numReviews: '10',
            description: 'high quality Pant',
        },
        {
            // _id:'7',
            name: 'Nike_Slim_shirt_7',
            slug: 'Nike_slim_shirt_7',
            category: 'Shirts',
            image: '/images/p1.jpg',
            price: 120,
            countinstock: 0,
            brand: 'Nike',
            rating: 4.0,
            numReviews: '10',
            description: 'high quality shirt',
        },
        {
            // _id:'8',
            name: 'Adidas_Slim_shirt_8',
            slug: 'Adidas_slim_shirt_8',
            category: 'Shirts',
            image: '/images/p2.jpg',
            price: 120,
            countinstock: 10,
            brand: 'Adidas',
            rating: 4.5,
            numReviews: '10',
            description: 'high quality shirt',


        },
        {
            // _id:'9',
            name: 'Nike_Slim_Pant_9',
            slug: 'nike_slim_Pant_9',
            category: 'Pants',
            image: '/images/p3.jpg',
            price: 120,
            countinstock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: '10',
            description: 'high quality Pant',
        },
        {
            // _id:'10',
            name: 'Adidas_Slim_Pant_10',
            slug: 'Adidas_slim_Pant_10',
            category: 'Shirts',
            image: '/images/p4.jpg',
            price: 120,
            countinstock: 10,
            brand: 'Adidas',
            rating: 4.5,
            numReviews: '10',
            description: 'high quality Pant',
        }
    ]
};

module.exports = data;